### ISSUE TITLE
Data driven entity generation by YAML definitions

### ISSUE THREAD

**Issue by eexsty** [HexaliteNetwork/java-edition#25]
# Entity generation by YAML definitions

**Table of contents:**
* [📰 Summary](#summary)
* [🤔 Motivations and the proposed solution](#motivations-and-the-proposed-solution)
* * [🦀 Rust](#rust)
* * [☕ Kotlin](#kotlin)
* [🌐 Examples](#examples)
* [🔗 Reference](#reference)
* [🤷 Final considerations](#final-considerations)

## Summary

We should create two code generators (one written in Kotlin and another written in Rust) which would generate entities based on fields defined in a YAML file.

## Motivations and the proposed solution

As mentioned in https://github.com/HexaliteNetwork/java-edition/issues/21, *"we need to create an entity data class in Kotlin with the same contents as Rust for the rest web client, this means that we would have duplicated code"*. **This feature would fix this problem and add more flexibility to entity changes.** We could also integrate this into the command-line interface for better management of this solution.

### Rust

Implementing this feature in Rust is really simple though, since we can simple use function-like procedural macros[¹](#reference) that read the YAML files, parse them and generate code.

### Kotlin

I still haven't thought of a better way to implement this, but I know we can use Gradle tasks and square/kotlinpoet[²](#reference) for code generation.

## Examples

**player.yml**
```yml
---
entities:
  - name: Player
    package: org.hexalite.generation.entity
    fields:
       uuid:
         kotlin: java.util.UUID
         rust: uuid::Uuid
       hexes:
         kotlin: Int
         rust: u32
       created_at:
         kotlin: kotlinx.datetime.Instant
         rust: chrono::DateTime<chrono::Utc>
```

## Reference

1. [Procedural macros](https://doc.rust-lang.org/reference/procedural-macros.html)
2. [square/kotlinpoet](https://github.com/square/kotlinpoet)
3. [YAML specification](https://yaml.org/spec/)

## Final considerations

Suggestions are appreciated for new sections in this issue, or if you have a better idea about how to structure it, feel free to let us know about it by commenting down below. Thank you for the attention.
